# Generated by Django 2.2.6 on 2020-02-19 22:40

import django.contrib.postgres.search
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255, unique=True)),
                ('search_document', django.contrib.postgres.search.SearchVectorField(null=True)),
                ('amount', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('amount_type', models.CharField(default='', max_length=10)),
                ('carbs', models.DecimalField(decimal_places=1, default=0, max_digits=10)),
                ('energy', models.DecimalField(decimal_places=1, default=0, max_digits=10)),
                ('fats', models.DecimalField(decimal_places=1, default=0, max_digits=10)),
                ('fibers', models.DecimalField(decimal_places=1, default=0, max_digits=10)),
                ('kcals', models.DecimalField(decimal_places=1, default=0, max_digits=10)),
                ('protein', models.DecimalField(decimal_places=1, default=0, max_digits=10)),
                ('salt', models.DecimalField(decimal_places=1, default=0, max_digits=10)),
                ('saturated_fats', models.DecimalField(decimal_places=1, default=0, max_digits=10)),
                ('sugars', models.DecimalField(decimal_places=1, default=0, max_digits=10)),
                ('unsaturated_fats', models.DecimalField(decimal_places=1, default=0, max_digits=10)),
                ('original_carbs', models.DecimalField(decimal_places=1, default=0, max_digits=10)),
                ('original_energy', models.DecimalField(decimal_places=1, default=0, max_digits=10)),
                ('original_fats', models.DecimalField(decimal_places=1, default=0, max_digits=10)),
                ('original_fibers', models.DecimalField(decimal_places=1, default=0, max_digits=10)),
                ('original_kcals', models.DecimalField(decimal_places=1, default=0, max_digits=10)),
                ('original_protein', models.DecimalField(decimal_places=1, default=0, max_digits=10)),
                ('original_salt', models.DecimalField(decimal_places=1, default=0, max_digits=10)),
                ('original_saturated_fats', models.DecimalField(decimal_places=1, default=0, max_digits=10)),
                ('original_sugars', models.DecimalField(decimal_places=1, default=0, max_digits=10)),
                ('original_unsaturated_fats', models.DecimalField(decimal_places=1, default=0, max_digits=10)),
                ('comments', models.TextField(default='', max_length=500)),
                ('used', models.PositiveSmallIntegerField(default=1)),
                ('tags', models.CharField(default='', max_length=510)),
                ('amount_list', models.CharField(default='', max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IngredientTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255, unique=True)),
                ('search_document', django.contrib.postgres.search.SearchVectorField(null=True)),
                ('used', models.SmallIntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
