# Generated by Django 2.2.6 on 2020-07-15 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0002_auto_20200219_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='amount',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=14),
        ),
    ]
