# Generated by Django 2.2.6 on 2020-07-22 09:57

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0003_auto_20200715_0906'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='ingredient',
            name='ingredients_search__bb053d_gin',
        ),
        migrations.RemoveIndex(
            model_name='ingredienttag',
            name='ingredients_search__bdc30f_gin',
        ),
        migrations.RenameField(
            model_name='ingredient',
            old_name='search_document',
            new_name='search_name',
        ),
        migrations.RenameField(
            model_name='ingredienttag',
            old_name='search_document',
            new_name='search_name',
        ),
        migrations.AddIndex(
            model_name='ingredient',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_name'], name='ingredients_search__983bfa_gin'),
        ),
        migrations.AddIndex(
            model_name='ingredienttag',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_name'], name='ingredients_search__3a830f_gin'),
        ),
    ]
