# Generated by Django 2.2.6 on 2020-02-19 22:40

import django.contrib.postgres.search
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255, unique=True)),
                ('search_document', django.contrib.postgres.search.SearchVectorField(null=True)),
                ('activity_level', models.CharField(choices=[('1.2', 'No exercise/sitting job'), ('1.375', 'Exercises 1-3 days/week/standing job'), ('1.55', 'Exercises 3-5 days/week'), ('1.725', 'Exercises 6-7 days/week'), ('1.9', 'Exercises twice a day')], default='NULL', max_length=5)),
                ('activity_level_readable', models.CharField(default='NULL', max_length=36)),
                ('age', models.PositiveSmallIntegerField(default=0)),
                ('bmr', models.PositiveSmallIntegerField(default=0)),
                ('comments', models.TextField(default='NULL', max_length=1000)),
                ('gender', models.CharField(choices=[('Female', 'Female'), ('Male', 'Male')], default='NULL', max_length=6)),
                ('height', models.PositiveSmallIntegerField(default=0)),
                ('maintenance', models.PositiveSmallIntegerField(default=0)),
                ('weight', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('email', models.CharField(default='NULL', max_length=100)),
                ('height_type', models.CharField(default='', max_length=10)),
                ('weight_type', models.CharField(default='', max_length=10)),
                ('height_add', models.PositiveSmallIntegerField(default=0)),
                ('weight_add', models.DecimalField(decimal_places=1, default=0, max_digits=3)),
                ('height_str', models.CharField(default='', max_length=20)),
                ('weight_str', models.CharField(default='', max_length=20)),
                ('height_cm', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
                ('weight_kg', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
