# Generated by Django 2.2.6 on 2020-02-29 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientaccounts', '0002_auto_20200219_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientaccount',
            name='activity_level',
            field=models.CharField(choices=[('1.2', 'No exercise --or-- sitting job'), ('1.375', 'Exercises 1-3 days/week --or-- standing job'), ('1.55', 'Exercises 3-5 days/week'), ('1.725', 'Exercises 6-7 days/week'), ('1.9', 'Exercises twice a day')], default='NULL', max_length=5),
        ),
        migrations.AlterField(
            model_name='clientaccount',
            name='activity_level_readable',
            field=models.CharField(default='NULL', max_length=43),
        ),
    ]
