# Generated by Django 2.2.6 on 2020-07-22 09:57

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientaccounts', '0003_auto_20200229_1440'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='clientaccount',
            name='clientaccou_search__510bbf_gin',
        ),
        migrations.RenameField(
            model_name='clientaccount',
            old_name='search_document',
            new_name='search_name',
        ),
        migrations.AddIndex(
            model_name='clientaccount',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_name'], name='clientaccou_search__5dbdfb_gin'),
        ),
    ]
