# Generated by Django 2.2.6 on 2020-02-19 22:40

import django.contrib.postgres.search
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ingredients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255, unique=True)),
                ('search_document', django.contrib.postgres.search.SearchVectorField(null=True)),
                ('carbs', models.DecimalField(decimal_places=1, default=0, max_digits=10)),
                ('categories', models.CharField(default='', max_length=510)),
                ('energy', models.DecimalField(decimal_places=1, default=0, max_digits=10)),
                ('fats', models.DecimalField(decimal_places=1, default=0, max_digits=10)),
                ('fibers', models.DecimalField(decimal_places=1, default=0, max_digits=10)),
                ('kcals', models.DecimalField(decimal_places=1, default=0, max_digits=10)),
                ('leanness', models.DecimalField(decimal_places=1, default=0, max_digits=10)),
                ('protein', models.DecimalField(decimal_places=1, default=0, max_digits=10)),
                ('salt', models.DecimalField(decimal_places=1, default=0, max_digits=10)),
                ('saturated_fats', models.DecimalField(decimal_places=1, default=0, max_digits=10)),
                ('sugars', models.DecimalField(decimal_places=1, default=0, max_digits=10)),
                ('unsaturated_fats', models.DecimalField(decimal_places=1, default=0, max_digits=10)),
                ('comment', models.TextField(default='')),
                ('add_ing_comment', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MealCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255, unique=True)),
                ('search_document', django.contrib.postgres.search.SearchVectorField(null=True)),
                ('used', models.SmallIntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MealIngredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_quantity', models.DecimalField(decimal_places=1, default=0, max_digits=10)),
                ('amount_type', models.CharField(default='', max_length=10)),
                ('quantity', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingredients.Ingredient')),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meals.Meal')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
