# Generated by Django 2.2.6 on 2020-02-19 22:40

from django.conf import settings
import django.contrib.postgres.indexes
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('meals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mealingredient',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mealcategory',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='meal',
            name='category',
            field=models.ManyToManyField(to='meals.MealCategory'),
        ),
        migrations.AddField(
            model_name='meal',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='mealcategory',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_document'], name='meals_mealc_search__99723f_gin'),
        ),
        migrations.AddIndex(
            model_name='meal',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_document'], name='meals_meal_search__544e9c_gin'),
        ),
    ]
