# Generated by Django 2.2.6 on 2020-07-22 09:57

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0002_auto_20200219_2240'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='meal',
            name='meals_meal_search__544e9c_gin',
        ),
        migrations.RemoveIndex(
            model_name='mealcategory',
            name='meals_mealc_search__99723f_gin',
        ),
        migrations.RenameField(
            model_name='meal',
            old_name='search_document',
            new_name='search_name',
        ),
        migrations.RenameField(
            model_name='mealcategory',
            old_name='search_document',
            new_name='search_name',
        ),
        migrations.AddIndex(
            model_name='meal',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_name'], name='meals_meal_search__244600_gin'),
        ),
        migrations.AddIndex(
            model_name='mealcategory',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_name'], name='meals_mealc_search__5f2d4b_gin'),
        ),
    ]
