# Generated by Django 2.2.6 on 2020-02-19 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_searchobject_owner'),
    ]

    operations = [
        migrations.DeleteModel(
            name='searchObject',
        ),
    ]
