# Generated by Django 2.2.6 on 2020-02-19 22:40

import django.contrib.postgres.search
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DayMealPlanTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_no', models.PositiveSmallIntegerField(default=0)),
                ('maintenance_fraction', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MealMealPlanTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(default=0)),
                ('meal_no', models.PositiveIntegerField(default=0)),
                ('hour', models.CharField(default='', max_length=4)),
                ('minutes', models.CharField(default='', max_length=2)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MealPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255, unique=True)),
                ('search_document', django.contrib.postgres.search.SearchVectorField(null=True)),
                ('duration', models.PositiveSmallIntegerField(default=0)),
                ('meal_plan', models.TextField(default='')),
                ('personal_data', models.TextField(default='')),
                ('template', models.CharField(default='', max_length=255)),
                ('start_weight', models.CharField(default='', max_length=15)),
                ('end_weight', models.CharField(default='', max_length=15)),
                ('start_maintenance', models.CharField(default='', max_length=15)),
                ('end_maintenance', models.CharField(default='', max_length=15)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MealPlanTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_document', django.contrib.postgres.search.SearchVectorField(null=True)),
                ('name', models.CharField(default='', max_length=255, unique=True)),
                ('template', models.TextField(default='')),
                ('status', models.CharField(default='Not working', max_length=23)),
                ('is_working', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
