# Generated by Django 2.2.6 on 2020-02-21 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mealplans', '0002_auto_20200219_2240'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealplan',
            name='form',
            field=models.TextField(default=''),
        ),
    ]
