# Generated by Django 2.2.6 on 2020-07-22 09:57

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mealplans', '0003_mealplan_form'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='mealplan',
            name='mealplans_m_search__ddf99e_gin',
        ),
        migrations.RemoveIndex(
            model_name='mealplantemplate',
            name='mealplans_m_search__a39ae2_gin',
        ),
        migrations.RenameField(
            model_name='mealplan',
            old_name='search_document',
            new_name='search_name',
        ),
        migrations.RenameField(
            model_name='mealplantemplate',
            old_name='search_document',
            new_name='search_name',
        ),
        migrations.AddIndex(
            model_name='mealplan',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_name'], name='mealplans_m_search__cf6345_gin'),
        ),
        migrations.AddIndex(
            model_name='mealplantemplate',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_name'], name='mealplans_m_search__761291_gin'),
        ),
    ]
